server:
  port: 8201

spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos注册中心地址
      discovery:
        cluster-name: SZ  # 集群名称：广州(GZ)集群 深圳（SZ）集群

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/cloud_user
      username: root
      password: 1234

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_
  type-aliases-package: com.cloud.user.model
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cloud.user: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS