server:
  port: 8201

spring:
  application:
    name: user-service

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/cloud_user
      username: root
      password: 1234

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_
  type-aliases-package: com.cloud.user.model
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cloud.user: debug
