server:
  port: 8101

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos注册中心地址
      discovery:
        cluster-name: SZ  # 集群名称：深圳（SZ）集群
        # namespace: ab348c8a-e5b9-49bf-81bf-3a447c134f73  # 命名空间：dev环境
        ephemeral: true  # 是否是临时实例
    loadbalancer: # 使用Nacos负载均衡策略：优先选择本地集群，然后在本地集群多个服务里按随机方式进行负载均衡
      nacos:
        enabled: true

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/cloud_order
      username: root
      password: 1234

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_
  type-aliases-package: com.cloud.order.model
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cloud.order: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#feign:
#  client:
#    config:
#      default:  # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置（如：user-service）
#        loggerLevel: FULL  # 日志级别
